import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ClientCookieHandler, ToastContainer } from "@/app/api/routes/route";

export const metadata = {
  title: "Singh Store",
  description: "Generated by create next app",
};

function ContainerContent({ children }) {
  return (
    <div className="container mx-auto">
      <ClientCookieHandler>{children}</ClientCookieHandler>
      <ToastContainer position="top-right" />
    </div>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <ContainerContent>{children}</ContainerContent>
        </main>
      </body>
    </html>
  );
}
