import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { cookies } from 'next/headers'
import { Navbar, ToastContainer } from "@/app/api/routes/route";

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookie = cookies().get("current_user_token");
  return (
    <html lang="en">
      <body>
        <main>
          <div className="container mx-auto">
            {cookie && <Navbar />}
            {children}
            <ToastContainer position="top-right" />
          </div>
        </main>
      </body>
    </html>
  );
}
